### ISSUE TITLE
Drag & Drop file sharing

### ISSUE THREAD

**Issue by maxfierke** [maxfierke/WaterCooler#17]

**Comment by jsJunky** [comment]
I ended up up implementing this following https://github.com/balderdashy/sails/issues/27 and using the jQuery-File-Upload that he specified. Also have markdown syntax implemented so I have it write a message with the uuid of the file and filename to the room. I'll look to clean up the code later this week and get it ready.

**Comment by morganlegal** [comment]
Hi @RonSalmon I'm struggling to implement balderdashy/sails#27 with the jQuery-File-Upload specified. Could you share some code? It would be very nice

**Comment by yf-hk** [comment]
Me too. Where should we upload user files to? I have searched a lot on the web but still haven't found the ideal solution. It would be great if someone can post an example

**Comment by maxfierke** [comment]
I've thought about this for a bit, I think there are a few options that I
can think of.

**Option 1:** Force MongoDB dependency. Use GridFS.
**Option 2:** Write generic interface for uploading to services such as S3,
Drop box, Google Drive, etc. Require service implementations of this
interface.
**Option 3:** Traditional uploading of files to public directory.

Option 2 is the most complex solution at this time, but its also the only
one which will retain the flexibility WaterCooler currently has, at the
cost of maintaining a few sample adapters, such as GridFS and S3.

Thanks,
Max
Sent by my Nexus 4
