### ISSUE TITLE
Passport integration

### ISSUE THREAD

**Issue by maxfierke** [maxfierke/WaterCooler#18]
Passport should be implemented to provide support for OAuth providers and other auth schemes.

**Comment by jsJunky** [comment]
I have passport local strategy working. See RonSalmon/WaterCooler@ebf415ee0bf54fb1802ac3bb91ad75721985625e

**Comment by maxfierke** [comment]
I took a quick look on my phone. It looks really great. I'll try it out later tonight. You should open a pull request in the meantime and I'll merge it in ASAP.

**Comment by maxfierke** [comment]
Closing this as Passport integration is now present and any further provider implementations should have their own GitHub issue.
