### ISSUE TITLE
HTTP Basic Auth (via Passport)

### ISSUE THREAD

**Issue by maxfierke** [maxfierke/WaterCooler#21]
This is mainly needed for Hubot to interact with WaterCooler via the API, but down the line it could be used for other things.

**Comment by jsJunky** [comment]
How far along are you with this? I can spend some time on this later tonight.

**Comment by jsJunky** [comment]
Also I can start adding in various oAuth strategies as well. Which ones would you like to add?

**Comment by maxfierke** [comment]
Not far. Granted, there's not much to do. I was just going to drop in the Passport HTTP basic auth call with the local strategy into the "authenticated" policy.

As far as OAuth strategies go, I'm most interested in Google, GitHub, and Twitter, but I'd like those to tie into the user model. I'll create a separate discussion issue to discuss how this should be done, since I'm looking for a little bit more than the ability to sign-up or login with an OAuth provider.

**EDIT:** See issue #24 for OAuth discussion.
