### ISSUE TITLE
Multiple clients/tabs open for a user adds multiple users to the list.

### ISSUE THREAD

**Issue by jsJunky** [maxfierke/WaterCooler#26]
Right now I am removing duplicates from the subscribers list in WaterCooler.handler.clientList and checking during the on.('presence' if the user being added or removed is already found in /subscribers. 

This does make room.clientcount off but still working on it.

**Comment by maxfierke** [comment]
Yeah. By default, Sails or Socket.io is opening a new socket for every connection. Perhaps there is a way to key sockets by user or session.

Another way would be to restructure how attendance is taken in a room, by grouping sockets by users, flatting them (basically what you've describe), and manually updating the count and storing it in either Redis or Mongo. This approach is probably quicker and easier to do, but I think I'd like to explore more around how Socket.io assigns sockets and how we may be able to influence that, as it will open doors to a few other forms of integrations.
